#!/bin/bash

initProject() {
    dir="$1"
    if [ ! -d "$dir" ]; then
        echo "Project directory $dir is not found"
        exit 1
    fi
    mkdir -p $dir'/app/controller'
    mkdir -p $dir'/app/dto'   
    mkdir -p $dir'/app/entity'
    mkdir -p $dir'/app/router/middleware'
    mkdir -p $dir'/app/model'
    mkdir -p $dir'/app/service'
    mkdir -p $dir'/app/rservice/rpci'
    mkdir -p $dir'/app/register'

    mkdir -p $dir'/bootstrap'
    mkdir -p $dir'/conf'   

    mkdir -p $dir'/deploy/config'
    mkdir -p $dir'/deploy/public/asset'
    mkdir -p $dir'/deploy/views'

    mkdir -p $dir'/dic'
    mkdir -p $dir'/driver'
    mkdir -p $dir'/enum'
    mkdir -p $dir'/job'             
    mkdir -p $dir'/console'
    mkdir -p $dir'/storage/logs'
    mkdir -p $dir'/storage/docs'
    mkdir -p $dir'/tests'
    mkdir -p $dir'/helper'

    touch $dir'/main.go'
}

# 临时方案不用包管理，防止一些网络条件差情况下，dep 包管理总是超时问题；
depEnsureAdd() {
    p=$(pwd)
    repo="$1"
    if [ -n "$repo" ]; then
        if [ ! -d "${p}/vendor" ]; then
            echo "vendor not found"
            exit 1
        fi

        # Luexu 的一律放到$GOPATH下共用
        if [ "${repo:0:17}" == "github.com/luexu/" ]; then 
            r="${GOPATH}/src/${repo}"
        else
            r="${p}/vendor/${repo}"
        fi

        if [ -d "${r}/.git" ]; then
            cd $r
            git pull origin master
        else
            if [ "${repo:0:11}" == "github.com/" ]; then
                echo "git clone https://${repo}.git $r"
                git clone "https://${repo}.git" $r
            else
                echo "git clone https://${repo} $r"
                git clone "https://${repo}" $r
            fi
        fi
    fi
}

updateLuexu() {
    l="${GOPATH}/src/github.com/luexu"
    cd $l
    repos="AaGo aenum dtype aorm"
    for repo in $repos; do
        r="${l}/${repo}"
        if [ -d "${r}/.git" ]; then
            cd "${r}"
            git pull origin master
        else
            echo "git clone https://github.com/luexu/${repo}.git ${r}"
            git clone "https://github.com/luexu/${repo}.git" "${r}"
        fi
        echo $r
    done
}

while getopts ':p:d:u' opt
do
    case $opt in
    d)
        depEnsureAdd ${OPTARG}
    ;;
    p)
        initProject ${OPTARG}
    ;;
    h)
        cat << EOF
Usage: AaGo [\$options]
    -p <dir>   : new project
EOF
        exit 0
    ;;
    u)
        updateLuexu
    ;;
    ?)
        echo "未知参数"
        exit 1
    ;;
    esac
done

shift $((OPTIND-1))